### ISSUE TITLE
Not showing correct battery status

### ISSUE THREAD

**Issue by devnore** [Sapd/HeadsetControl#339]
### Description

Hi Denis!

First of all, it is awesome to see the formatting (yaml/json/env) added 

But I ran into an issue with the output that I guess is specific to either my specific model or Steelseries in general as the functionality  was discussed in #271 and seemed to be working with Corsair Void.

The issue:
My battery status is always showing `BATTERY_AVAILABLE` regardless of if it is charging/discharging/off the only value that changes (when turned off is the battery level which reports 0 (and that should be fine)

On, Connected/Charging
``` 
name: "HeadsetControl"
version: "3.0.0-1-g0005a0a"
api_version: "1.0"
hidapi_version: "0.11.2"
device_count: 1
devices:
  - status: "success"
    device: "SteelSeries Arctis (7/Pro)"
    vendor: "SteelSeries "
    product: "SteelSeries Arctis 7"
    id_vendor: "0x1038"
    id_product: "0x12ad"
    capabilities:
      - CAP_SIDETONE
      - CAP_BATTERY_STATUS
      - CAP_LIGHTS
      - CAP_INACTIVE_TIME
      - CAP_CHATMIX_STATUS
    capabilities_str:
      - sidetone
      - battery
      - lights
      - inactive time
      - chatmix
    battery:
      status: "BATTERY_AVAILABLE"
      level: 70
    chatmix: 53
```

Off, Connected/Charging
```name: "HeadsetControl"
version: "3.0.0-1-g0005a0a"
api_version: "1.0"
hidapi_version: "0.11.2"
device_count: 1
devices:
  - status: "success"
    device: "SteelSeries Arctis (7/Pro)"
    vendor: "SteelSeries "
    product: "SteelSeries Arctis 7"
    id_vendor: "0x1038"
    id_product: "0x12ad"
    capabilities:
      - CAP_SIDETONE
      - CAP_BATTERY_STATUS
      - CAP_LIGHTS
      - CAP_INACTIVE_TIME
      - CAP_CHATMIX_STATUS
    capabilities_str:
      - sidetone
      - battery
      - lights
      - inactive time
      - chatmix
    battery:
      status: "BATTERY_AVAILABLE"
      level: 0
    chatmix: 64
```

Off, Disconnected
``` 
---
name: "HeadsetControl"
version: "3.0.0-1-g0005a0a"
api_version: "1.0"
hidapi_version: "0.11.2"
device_count: 1
devices:
  - status: "success"
    device: "SteelSeries Arctis (7/Pro)"
    vendor: "SteelSeries "
    product: "SteelSeries Arctis 7"
    id_vendor: "0x1038"
    id_product: "0x12ad"
    capabilities:
      - CAP_SIDETONE
      - CAP_BATTERY_STATUS
      - CAP_LIGHTS
      - CAP_INACTIVE_TIME
      - CAP_CHATMIX_STATUS
    capabilities_str:
      - sidetone
      - battery
      - lights
      - inactive time
      - chatmix
    battery:
      status: "BATTERY_AVAILABLE"
      level: 0
    chatmix: 64
```

### Headset Name

SteelSeries Arctis 7

### On which OS does the problem happen?

Linux

### Device information

<details>
 <summary>Detailed Device Information</summary>

 ```
$>headsetcontrol --dev -- --list --device 0x1038:0x12ad
Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0xc Usageid: 0x1

Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0xff43 Usageid: 0x202

Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0xff00 Usageid: 0x1

Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0xff00 Usageid: 0xa

Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0xff00 Usageid: 0x22

Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0xff00 Usageid: 0xa

Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0xff00 Usageid: 0x22

Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0xff00 Usageid: 0xa

Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0xff00 Usageid: 0x22

Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0xff00 Usageid: 0xa

Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0xff00 Usageid: 0x22

Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0xff00 Usageid: 0xa

Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0xff00 Usageid: 0xc

Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0x1 Usageid: 0x3a

Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0xff00 Usageid: 0xc

Device Found
  VendorID: 0x1038
 ProductID: 0x12ad
  path: /dev/hidraw10
  serial_number: 
  Manufacturer: SteelSeries 
  Product:      SteelSeries Arctis 7
  Interface:    5
  Usage-Page: 0x1 Usageid: 0x3a
 ```

</details>
